name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Smoke test import
        run: |
          python - <<'PY'
          import app
          print('App imported, routes:', [r.rule for r in app.app.url_map.iter_rules()][:5])
          PY
      - name: Run tests
        run: |
          pytest -q || true  # placeholder: laat niet falen totdat tests bestaan
